apiVersion: v1
kind: Secret
metadata:
  name: export-secret
  namespace: analytics-export
type: Opaque
data:
  # Значения в base64. Можно закодировать: echo -n "password" | base64
  DB_USER: cG9zdGdyZXM=        # postgres
  DB_PASSWORD: cG9zdGdyZXMxMjM=  # postgres123